version: '3'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  rabbitmq:
    image: 'bitnami/rabbitmq'
    ports:
      - '5672:5672'
  gerapy-rabbitmq-example:
    container_name: 'gerapy-rabbitmq-example'
    restart: always
    build: .
    image: 'germey/gerapy-rabbitmq-example'
    command: 'scrapy crawl movie'
    environment:
      REDIS_URL: 'redis://@redis:6379'
      RABBITMQ_CONNECTION_PARAMETERS: 'host=rabbitmq'
    depends_on:
      - redis
      - rabbitmq